package bili

type AutoGenerated struct {
    Code    int    `json:"code"`
    Message string `json:"message"`
    TTL     int    `json:"ttl"`
    Data    struct {
        Cursor struct {
            IsEnd bool `json:"is_end"`
        }
        Replies []struct {
            Content struct {
                Message string `json:"message"`
            } `json:"content"`
            Replies      []any `json:"replies"`
            ReplyControl struct {
                MaxLine  int    `json:"max_line"`
                TimeDesc string `json:"time_desc"`
                Location string `json:"location"`
            } `json:"reply_control"`
            Folder struct {
                HasFolded bool   `json:"has_folded"`
                IsFolded  bool   `json:"is_folded"`
                Rule      string `json:"rule"`
            } `json:"folder"`
            TrackInfo string `json:"track_info"`
        } `json:"replies"`
    } `json:"data"`
}
